# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build
FROM node:18-slim AS build

# Set the working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Production
FROM node:18-slim

# Set the working directory
WORKDIR /app

# Copy package.json and only necessary artifacts from the build stage
COPY --from=build /app/package.json ./
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules

# Set environment variables (placeholder values)
ENV STEAMGRIDDB_API_KEY=""

# The command to run the server
ENTRYPOINT ["node", "dist/index.js"]
